export const genresArray = [
  { name: "Action", value: 4 },
  { name: "Indie", value: 51 },
  { name: "Adventure", value: 3 },
  { name: "RPG", value: 5 },
  { name: "Strategy", value: 10 },
  { name: "Shooter", value: 2 },
  { name: "Casual", value: 40 },
  { name: "Simulation", value: 14 },
  { name: "Puzzle", value: 7 },
  { name: "Arcade", value: 11 },
  { name: "Platformer", value: 83 },
  { name: "Racing", value: 1 },
  { name: "Sports", value: 15 },
  { name: "MMORPG", value: 59 },
  { name: "Fighting", value: 6 },
  { name: "Family", value: 19 },
  { name: "Board Games", value: 28 },
  { name: "Educational", value: 34 },
  { name: "Card", value: 17 },
];

export const platformsArray = [
  {
    desktop: [
      { name: "PC", value: 4 },
      { name: "macOS", value: 5 },
      { name: "Linux", value: 6 },
      { name: "Classic Macintosh", value: 55 },
    ],
    sony: [
      { name: "PS5", value: 187 },
      { name: "PS4", value: 18 },
      { name: "PS3", value: 16 },
      { name: "PS2", value: 15 },
      { name: "PS1", value: 27 },
      { name: "PS Vita", value: 19 },
      { name: "PSP", value: 17 },
    ],
    nintendo: [
      { name: "Nintendo Switch", value: 7 },
      { name: "Wii U", value: 10 },
      { name: "Wii", value: 11 },
      { name: "Gamecube", value: 105 },
      { name: "Nintendo 64", value: 83 },
      { name: "SNES", value: 79 },
      { name: "NES", value: 49 },
      { name: "3DS", value: 8 },
      { name: "DSi", value: 13 },
      { name: "DS", value: 9 },
      { name: "Game Boy Advance", value: 24 },
      { name: "Game Boy Color", value: 43 },
      { name: "Game Boy", value: 26 },
    ],
    microsoft: [
      { name: "Xbox Series S/X", value: 186 },
      { name: "Xbox One", value: 1 },
      { name: "Xbox 360", value: 14 },
      { name: "Xbox", value: 80 },
    ],
    sega: [
      { name: "Dreamcast", value: 106 },
      { name: "Saturn", value: 107 },
      { name: "SEGA CD", value: 119 },
      { name: "SEGA 32X", value: 117 },
      { name: "Genesis", value: 167 },
      { name: "Master System", value: 74 },
      { name: "Game Gear", value: 77 },
    ],
    mobile: [
      { name: "Android", value: 21 },
      { name: "iOS", value: 3 },
    ],
    retro: [
      { name: "Commodore/Amiga", value: 166 },
      { name: "3DO", value: 111 },
      { name: "Neo Geo", value: 12 },
      { name: "Jaguar", value: 112 },
      { name: "Apple II", value: 41 },
      { name: "Atari 7800", value: 28 },
      { name: "Atari 5200", value: 31 },
      { name: "Atari 2600", value: 23 },
      { name: "Atari Flashback", value: 22 },
      { name: "Atari 8-bit", value: 25 },
      { name: "Atari ST", value: 34 },
      { name: "Atari Lynx", value: 46 },
      { name: "Atari XEGS", value: 50 },
    ],
  },
];

export const storesArray = [
  { name: "Steam", value: 1 },
  { name: "Playstation Store", value: 3 },
  { name: "Xbox Store", value: 2 },
  { name: "App Store", value: 4 },
  { name: "GOG", value: 5 },
  { name: "Nintendo Store", value: 6 },
  { name: "Xbox 360 Store", value: 7 },
  { name: "Google Play", value: 8 },
  { name: "itch.io", value: 9 },
  { name: "Epic Games", value: 11 },
];
